#       _____
#  _   |_   _|__  _ __  ___
# | | | || |/ _ \| '_ \/ __|
# | |_| || | (_) | |_) \__ \
#  \__, ||_|\___/| .__/|___/
#  |___/         |_|
# Discord: discord.ystoreplugins.com.br
# Site: ystoreplugins.com.br
#

# Modo de depuração para correção de problemas no plugin.
debug-mode: false

#      ___      _        _
#     /   \__ _| |_ __ _| |__   __ _ ___  ___
#    / /\ / _` | __/ _` | '_ \ / _` / __|/ _ \
#   / /_// (_| | || (_| | |_) | (_| \__ \  __/
#  /___,' \__,_|\__\__,_|_.__/ \__,_|___/\___|
#
# Configurações do banco de dados.

database:
  # Determina o tipo de banco de dados. Valores válidos: [SQLITE, MYSQL, HIKARI (recomendado)]
  storage-type: SQLITE

  # Dados para conexão ao banco de dados MYSQL.
  data:
    # Endereço de conexão do banco de dados. [EX: 127.0.0.1]
    host: localhost
    # Porta de conexão do banco de dados. [EX: 3306]
    port: 3306
    # Nome do banco de dados a ser conectado. [EX: minecraft]
    database: ''
    # Usuário de conexão. [EX: root]
    username: ''
    # Senha do usuário de conexão: [EX: 123]
    password: ''

# Tempo para atualizar a lista de tops
# em segundos
top-list-tick: 1800

# Tempo para atualizar as entidades
# em segundos
top-entity-tick: 1810

# Ativar o NPC ficar olhando pro player
look-close: true

# Configuração do menu de TOP
top-menu:
  # em segundos
  time: 600
  player-format: '%ytopspapiaddon_luckperms_prefix% {player}'

# Mensagem de anúncio de jogadores do top
top-message:
  enable: true
  # em segundos
  time: 600
  #
  # PLACEHOLDERS DISPONÍVEIS:
  # {value_<TYPE>_formatted}, {value_<TYPE>_time}, {value_<TYPE>_kdr}
  #
  # TYPES:
  # VAULT, YPLANTACOES_MOEDAS, YMAQUINAS_VALOR, YTEMPOONLINE_TEMPO, YLOJAS_VISITAS, YEVENTOS_GANHADOS, YMINAS_QUEBRADOS, YMINAS_BLOCOS, YBOSSES_MATADOS, YNEWBOSSES_MATADOS, YMISSOES_ORDEM, YALMAS_ALMAS, YKILLRANK_KILLS,
  # YKILLSYSTEM_XP, YKILLSYSTEM_MONEY, YKILLSYSTEM_KILLS, YKILLSYSTEM_KDR, YRANKUP_PRESTIGIO, YRANKUP_FRAGMENTOS, YSPAWNERS_COMPRADOS, YSPAWNERSSHOP_COMPRADOS, YSPAWNERSSHOP_LIMITE, YCLANS_MONEY, YCLANS_KDR, YCLANS_MAQUINAS,
  # YCLANS_SPAWNERS, MCMMO_TODOS, MCMMO_ALQUIMIA, MCMMO_ESPADAS, MCMMO_ARQUERIA, MCMMO_MINERACAO, MCMMO_EXCAVACAO, MCMMO_MACHADOS, MCMMO_REPARACAO, MCMMO_ACROBACIA, YPOINTS_PONTOS, YPESCA_COINS, YPESCA_PESCADOS, YGUERRA_GANHADAS,
  # YGUERRA_CLAN_GANHADAS, YCHAIN_KILL, YCHAIN_KILLSTREAK, YCHAIN_KDR, YCHAIN_TEMPO, YCRATESVIRTUAIS_ABERTAS, YRECOMENDAR_RECOMENDADOS, YCLANS_KILLS, YCLANS_DEATHS, YVIPS_ATIVADOS, YVIPS_CREDITOS, YMITO_TIMES, YMITO_TOTAL_TIME,
  # YMINASPACKETS_QUEBRADOS, YMINASPACKETS_BLOCOS
  #
  player-format: '%ytopspapiaddon_luckperms_prefix% {player}'
  message: |

    &aVeja os jogadores que se destacam no servidor!
    &7(Clique na mensagem para acessar o TOP escolhido)

    <click:run_command:/money top><hover:show_text:"<green>Clique para acessar o TOP</green>"><dark_gray>-></dark_gray> <green>{player_VAULT}</green> <dark_gray>-</dark_gray> <dark_green>$</dark_green><white>{value_VAULT_formatted}</white></hover></click>